name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server
        # Your existing deployment steps

      - name: Deploy Nginx configuration
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -P $PORT -i private_key.pem -o StrictHostKeyChecking=no nginx/AirdropFarmer.conf $SERVER_USER@$SERVER_IP:/tmp/AirdropFarmer.conf
          ssh -p $PORT -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo mv /tmp/AirdropFarmer.conf /etc/nginx/sites-available/AirdropFarmer && sudo ln -sf /etc/nginx/sites-available/AirdropFarmer /etc/nginx/sites-enabled/ && sudo systemctl restart nginx"
          rm -f private_key.pem
